### ISSUE TITLE
egui::RichText size is broken.

### ISSUE THREAD

**Issue by qianzhang5** [hakolao/egui_winit_vulkano#11] opened 2022-03-31 23:05 UTC
After egui::RichText::new(text).size(x) is called, font display is screwed up, if text is updated text string.
how to reproduce: 
  with example code minimal.rs, add  ui.label(egui::RichText::new(format!("** {} **", count)).size(60.0) );  into line81. 

code snipper:
                        ui.separator();
                        ui.columns(2, |columns| {
                            ScrollArea::vertical().id_source("source").show(
                                &mut columns[0],
                                |ui| {
                                    // ui.add(
                                    //     TextEdit::multiline(&mut code).font(TextStyle::Monospace),
                                    // );
                                    ui.label(
                                        egui::RichText::new(format!("** {} **", count)).size(60.0)
                                    );
                                    count += 1;
                                },
                            );
                            ScrollArea::vertical().id_source("rendered").show(
                                &mut columns[1],
                                |ui| {
                                    egui_demo_lib::easy_mark::easy_mark(ui, &code);
                                },
                            );
                        });

**Comment by qianzhang5** [comment] 2022-03-31 23:11
<img width="1306" alt="rich-text" src="https://user-images.githubusercontent.com/12856704/161164209-b6e71fca-b020-4047-b49f-f38479e1b377.png">

**Comment by hakolao** [comment] 2022-04-01 10:47
Thanks for reporting, I’ll look into it

**Comment by hakolao** [comment] 2022-04-04 17:57
I'm unable to reproduce, can you retry? @qianzhang5. 

![image](https://user-images.githubusercontent.com/12234005/161603249-83a4ae9b-8aa6-4300-be5c-f608a153dcea.png)

It could be related to the 0.17 egui update I did, but I would need better reproduction steps.

**Comment by qianzhang5** [comment] 2022-04-05 05:28
[egui-bug-reproduce.zip](https://github.com/hakolao/egui_winit_vulkano/files/8415113/egui-bug-reproduce.zip)

**Comment by qianzhang5** [comment] 2022-04-05 05:35
Above it's my test code.
I have tested egui 0.17.0 in another project. I don't see the problem.

**Comment by hakolao** [comment] 2022-04-05 10:00
Thanks, I’ll retry

**Comment by hakolao** [comment] 2022-04-05 14:14
I'll try to figure out how to fix this one..., managed to repro now

**Comment by hakolao** [comment] 2022-04-07 12:09
I wasn't properly updating the partial font update, which is why the `RichText` failed. It should be fixed now in the master branch @qianzhang5 

It required some refactors :)

**Closed as completed** 2022-04-07 12:23 UTC
